name: Build and Docker Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Maven Build and Docker
      run: |
          mvn clean package -B -DskipTests --file pom.xml -T $(nproc)
          docker build --compress -t docker.pkg.github.com/iesb-dispositivos-moveis-2019-2/scrum-deck-backend/scrum-deck-backend:$GITHUB_ACTION .
          docker push docker.pkg.github.com/iesb-dispositivos-moveis-2019-2/scrum-deck-backend/scrum-deck-backend:$GITHUB_ACTION


